import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getCurrentUser } from '@/lib/auth';
import * as XLSX from 'xlsx';

// GET /api/reports/export?tab=overview|stock|sales|transfer|adjustment|incentive&entityId=&from=&to=
// Returns an .xlsx file with the selected report tab as a flat table.
// Uses the same query logic as /api/reports but converts to a spreadsheet.

export async function GET(request: NextRequest) {
  try {
    const currentUser = await getCurrentUser(request);
    if (!currentUser) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });

    const searchParams = request.nextUrl.searchParams;
    const entityId = searchParams.get('entityId') || '';
    const fromStr = searchParams.get('from');
    const toStr = searchParams.get('to');
    const tab = searchParams.get('tab') || 'overview';

    const to = toStr ? new Date(toStr) : new Date();
    const from = fromStr ? new Date(fromStr) : new Date(to.getTime() - 30 * 24 * 60 * 60 * 1000);
    if (isNaN(from.getTime()) || isNaN(to.getTime())) {
      return NextResponse.json({ error: 'Invalid date range' }, { status: 400 });
    }
    to.setHours(23, 59, 59, 999);

    const userEntityIds =
      currentUser.role === 'admin' || currentUser.role === 'manager'
        ? null
        : currentUser.entityAccess.map((ea) => ea.entityId);

    if (userEntityIds && userEntityIds.length === 0) {
      return NextResponse.json({ error: 'No entity access' }, { status: 403 });
    }

    const entityFilter = (field: string) => {
      const f: Record<string, unknown> = {};
      if (entityId) f[field] = entityId;
      else if (userEntityIds) f[field] = { in: userEntityIds };
      return f;
    };
    const dateFilter = (field: string) => ({ [field]: { gte: from, lte: to } });

    // Build sheets based on the requested tab
    const sheets: { name: string; rows: Record<string, unknown>[] }[] = [];

    // Always include a summary sheet
    const summary: Record<string, unknown>[] = [{
      'Report': tab.charAt(0).toUpperCase() + tab.slice(1),
      'Generated At': new Date().toLocaleString(),
      'From': from.toLocaleDateString(),
      'To': to.toLocaleDateString(),
      'Entity Filter': entityId ? 'Single entity' : 'All accessible entities',
      'Generated By': currentUser.displayName,
    }];
    sheets.push({ name: 'Summary', rows: summary });

    if (tab === 'overview' || tab === 'stock') {
      const stocks = await db.stock.findMany({
        where: entityId ? { entityId } : userEntityIds ? { entityId: { in: userEntityIds } } : {},
        include: { item: true, entity: true },
      });
      const stockRows = stocks.map(s => ({
        'Entity': s.entity?.name || '-',
        'Item Name': s.item?.itemName || '-',
        'Barcode': s.item?.barcode || '',
        'Item Code': s.item?.itemCode || '',
        'Group': s.item?.group || '',
        'Sub Group': s.item?.subGroup || '',
        'UoM': s.item?.uom || 'PCS',
        'Quantity': s.quantity,
        'Unit Price': s.item?.price || 0,
        'Total Value': s.quantity * (s.item?.price || 0),
      }));
      sheets.push({ name: 'Stock', rows: stockRows });
    }

    if (tab === 'overview' || tab === 'sales') {
      const orders = await db.salesOrder.findMany({
        where: { ...entityFilter('entityId'), ...dateFilter('createdAt') },
        include: {
          entity: { select: { name: true } },
          customer: { select: { name: true, phone: true } },
          salesPerson: { select: { name: true, designation: true } },
          items: { include: { item: { select: { itemName: true } } } },
          payments: true,
        },
      });
      const salesRows = orders.map(o => {
        const grandTotal = o.items.reduce((s, it) => s + it.quantity * it.unitPrice + (it.makingEntries || []).reduce((m: number, me: any) => m + me.quantity * me.unitPrice, 0), 0);
        const totalPaid = (o.payments || []).reduce((s, p) => s + p.amount, 0);
        return {
          'Sales No': o.salesNo,
          'Entity': o.entity?.name || '-',
          'Order Date': new Date(o.orderDate || o.createdAt).toLocaleDateString(),
          'Customer': o.customer?.name || '-',
          'Customer Phone': o.customer?.phone || '',
          'Sales Person': o.salesPerson?.name || '',
          'Status': o.status,
          'Item Count': o.items.length,
          'Grand Total': grandTotal,
          'Total Paid': totalPaid,
          'Due': grandTotal - totalPaid,
          'Notes': o.notes || '',
        };
      });
      sheets.push({ name: 'Sales Orders', rows: salesRows });
    }

    if (tab === 'overview' || tab === 'transfer') {
      const transfers = await db.transfer.findMany({
        where: { ...entityFilter('fromEntityId'), ...dateFilter('createdAt') },
        include: { item: true, fromEntity: true, toEntity: true },
      });
      const transferRows = transfers.map(t => ({
        'Item': t.item?.itemName || '-',
        'From Entity': t.fromEntity?.name || '-',
        'To Entity': t.toEntity?.name || '-',
        'Quantity': t.quantity,
        'Status': t.status,
        'Date': new Date(t.createdAt).toLocaleDateString(),
        'Notes': t.notes || '',
      }));
      sheets.push({ name: 'Transfers', rows: transferRows });
    }

    if (tab === 'overview' || tab === 'adjustment') {
      const adjustments = await db.itemAdjustment.findMany({
        where: { ...entityFilter('entityId'), ...dateFilter('createdAt') },
        include: { item: true, entity: true },
      });
      const adjRows = adjustments.map(a => ({
        'Entity': a.entity?.name || '-',
        'Item': a.item?.itemName || '-',
        'Type': a.adjustmentType,
        'Quantity': a.quantity,
        'Reason': a.reason,
        'Date': new Date(a.createdAt).toLocaleDateString(),
      }));
      sheets.push({ name: 'Adjustments', rows: adjRows });
    }

    if (tab === 'overview' || tab === 'incentive') {
      const incentives = await db.incentive.findMany({
        where: { ...entityFilter('entityId'), ...dateFilter('createdAt') },
        include: { item: true, entity: true, tailor: true },
      });
      const incRows = incentives.map(i => ({
        'Entity': i.entity?.name || '-',
        'Item': i.item?.itemName || '-',
        'Tailor': i.tailor?.name || '-',
        'Type': i.type,
        'Amount': i.amount,
        'Status': i.status,
        'Date': new Date(i.createdAt).toLocaleDateString(),
        'Notes': i.notes || '',
      }));
      sheets.push({ name: 'Incentives', rows: incRows });
    }

    // Build the workbook
    const wb = XLSX.utils.book_new();
    for (const sheet of sheets) {
      const ws = XLSX.utils.json_to_sheet(sheet.rows.length > 0 ? sheet.rows : [{ 'Info': 'No data for this period' }]);
      // Auto-size columns
      const cols = Object.keys(sheet.rows[0] || { 'Info': '' });
      ws['!cols'] = cols.map(c => ({ wch: Math.max(c.length + 2, 15) }));
      XLSX.utils.book_append_sheet(wb, ws, sheet.name.slice(0, 31));
    }

    const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
    return new NextResponse(buf, {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="report-${tab}-${new Date().toISOString().split('T')[0]}.xlsx"`,
      },
    });
  } catch (error) {
    console.error('Reports export error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
